### ISSUE TITLE
Remove lodash dependency

### ISSUE THREAD

**Issue by gyzerok** [RisingStack/graffiti-mongoose#16]
What do you think about removing lodash?

**Comment by hekike** [comment]
@gyzerok I don't understand this question. From where do you get it?

**Comment by hekike** [comment]
Ok I understand now, so you want to remove it.

Why? Do you think it's a good idea?

**Comment by gyzerok** [comment]
@hekike I am now sure, but isnt it better to have as minimal dependency list as possible? It looks like you use just a few lodash functions in your code.

**Comment by hekike** [comment]
@gyzerok yes it's good to keep it on minimum but I'm iterating over Objects instead of Arrays and in thnk `lodash` is doing it well. If we want to optimise it then in `lodash` it's possible to require only the specific functions and decrease the bundled code size. I think it would be a better strep.

**Comment by hekike** [comment]
@gyzerok maybe turning or mapish Object -s to ES6 `Map` etc. would help us to use `for of` and other ES6 features with babel and would make it possible. I will investigate it later.

**Comment by gyzerok** [comment]
@hekike suppose its better use more functional approach. ```for of``` is an imperative one :)

**Comment by hekike** [comment]
Ok then I close this issue.
